preset: recommended

risky: true

enabled:
  - unalign_double_arrow
  - ternary_to_null_coalescing
  - no_alternative_syntax
  - concat_with_spaces

disabled:
  - align_double_arrow
  - concat_without_spaces
