<?php

return array(
    MCRYPT_3DES,
    MCRYPT_BLOWFISH,
    MCRYPT_BLOWFISH_COMPAT,
    MCRYPT_DES,
    MCRYPT_LOKI97,
    MCRYPT_CAST_128,
    MCRYPT_CAST_256,
    MCRYPT_RC2,
    MCRYPT_RIJNDAEL_128,
    MCRYPT_RIJNDAEL_192,
    MCRYPT_RIJNDAEL_256,
    MCRYPT_SAFERPLUS,
    MCRYPT_SERPENT,
    MCRYPT_TRIPLEDES,
    MCRYPT_TWOFISH,
    MCRYPT_XTEA,
);
